---
- name: "start kafka"
  service: name=kafka state=started
  become_user: root

- name: "stop kafka"
  service: name=kafka state=stopped
  become_user: root

- name: "restart kafka"
  service: name=kafka state=restarted
  become_user: root

